# Trigger for all pull requests 
# (this is achieved by not mentioning the pr: attribute at all..., see https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pull-request-validation)

# Don't trigger on tag/branch changes
trigger: none

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  displayName: Run NUKE Build (Pack)
  inputs:
    targetType: 'filePath'
    filePath: build.ps1
    arguments: Package
# This task publishes the test results to Azure DevOps, so that the results are visible in de "Tests" tab of the build
- task: PublishTestResults@2
  condition: always()
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'